# Generated by Django 4.1.1 on 2022-09-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='diary',
            fields=[
                ('diary_id', models.AutoField(primary_key=True, serialize=False)),
                ('diary_date', models.DateTimeField(auto_now_add=True)),
                ('diary_title', models.CharField(max_length=20)),
                ('diary_content', models.TextField(max_length=200)),
                ('diary_todayme', models.CharField(blank=True, max_length=20, null=True)),
                ('diary_tomorrowme', models.CharField(blank=True, max_length=20, null=True)),
                ('diary_img', models.ImageField(blank=True, null=True, upload_to=None)),
            ],
        ),
    ]
